#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app_src=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app_src=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_APPS_DIR/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

if [[ -n "$2" ]]; then
  app_dest=$2
else
  echo "Missing new app name" >&2
  exit 1
fi

# Let plushu-apps' hook move the app directory-
# other plugins will move directories outside the app directory
# (the repo, nginx config, SSL)
"$PLUSHU_ROOT/lib/plushook" rename-app "$app_src" "$app_dest"

# Redeploy as this may affect things like default domain
"$PLUSHU_ROOT/lib/plushook" deploy-app "$app_dest"
