#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
app_dir=$PLUSHU_APPS_DIR/$app

mkdir -p "$app_dir"

# If running as root
if [[ "$EUID" == 0 ]]; then
  # make sure plushu owns the app
  chown -R "$PLUSHU_USER" "$app_dir"
fi
